import { createServer, type IncomingMessage, type ServerResponse } from "node:http";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import { z } from "zod/v3";

const port = Number(process.env.MCP_SMOKE_PORT ?? 8787);
const endpointPath = "/mcp";

const createMcpServer = () => {
  const mcpServer = new McpServer({
    name: "agents-smoke-mcp",
    version: "0.1.0",
  });

  const registerTool = mcpServer.registerTool.bind(mcpServer) as (
    name: string,
    config: {
      title: string;
      description: string;
      inputSchema: { symbols: z.ZodDefault<z.ZodArray<z.ZodString>> };
      annotations: {
        readOnlyHint: boolean;
        destructiveHint: boolean;
        idempotentHint: boolean;
        openWorldHint: boolean;
      };
    },
    handler: (input: { symbols: string[] }) => Promise<{
      content: Array<{ type: "text"; text: string }>;
    }>,
  ) => void;

  registerTool(
    "get_watchlist_news",
    {
      title: "Get watchlist news",
      description:
        "Returns deterministic read-only market news for the supplied watchlist symbols.",
      inputSchema: {
        symbols: z.array(z.string()).default(["AAPL", "MSFT"]),
      },
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false,
      },
    },
    async ({ symbols }: { symbols: string[] }) => ({
      content: [
        {
          type: "text",
          text: JSON.stringify(
            {
              asOf: new Date().toISOString(),
              symbols,
              items: symbols.map((symbol) => ({
                symbol,
                headline: `${symbol} product and earnings watch remains steady`,
                summary:
                  "Deterministic smoke-test news item generated by the local MCP server.",
              })),
            },
            null,
            2,
          ),
        },
      ],
    }),
  );

  return mcpServer;
};

const handleRequest = async (
  request: IncomingMessage,
  response: ServerResponse,
) => {
  if (!request.url?.startsWith(endpointPath)) {
    response.writeHead(404, { "content-type": "application/json" });
    response.end(JSON.stringify({ error: "not_found" }));
    return;
  }

  try {
    const mcpServer = createMcpServer();
    const transport = new StreamableHTTPServerTransport({
      sessionIdGenerator: undefined,
    });
    await mcpServer.connect(transport);
    await transport.handleRequest(request, response);
    response.on("close", () => {
      void transport.close();
      void mcpServer.close();
    });
  } catch (error) {
    console.error("Smoke MCP request failed", error);
    if (!response.headersSent) {
      response.writeHead(500, { "content-type": "application/json" });
      response.end(
        JSON.stringify({
          error: "mcp_request_failed",
          message: error instanceof Error ? error.message : "Unknown MCP error",
        }),
      );
    }
  }
};

const main = async () => {
  const httpServer = createServer(handleRequest);
  httpServer.listen(port, "127.0.0.1", () => {
    console.log(
      `Smoke MCP server listening at http://127.0.0.1:${port}${endpointPath}`,
    );
  });
};

void main();
